### ISSUE TITLE
Flip card does not listen for audio plugin changes

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-flipcard-audio#25]
To reproduce:

Setup course with audio enabled and a flip card component.
Open the course, audio should play on flipcard.
Turn off audio via draw audio controls.
Audio in flipcard still plays.

Versions:
FW v2.0.15
Audio v3.2.2
Flipcard v2.0.17

**Comment by RobertPeek** [comment]
This turned out to be a bug in the audio plugin.
